/// Event type alias.
pub type EventType = String;
/// Websocket opcode alias.
pub type OpCode = u8;

use super::events::opcodes;

pub const WS_DISPATCH_EVENT: OpCode = opcodes::DISPATCH;
pub const WS_HEARTBEAT: OpCode = opcodes::HEARTBEAT;
pub const WS_IDENTIFY: OpCode = opcodes::IDENTIFY;
pub const WS_RESUME: OpCode = opcodes::RESUME;
pub const WS_RECONNECT: OpCode = opcodes::RECONNECT;
pub const WS_INVALID_SESSION: OpCode = opcodes::INVALID_SESSION;
pub const WS_HELLO: OpCode = opcodes::HELLO;
pub const WS_HEARTBEAT_ACK: OpCode = opcodes::HEARTBEAT_ACK;
pub const HTTP_CALLBACK_ACK: OpCode = 12;
pub const HTTP_CALLBACK_VALIDATION: OpCode = 13;

pub const EVENT_GUILD_CREATE: &str = "GUILD_CREATE";
pub const EVENT_GUILD_UPDATE: &str = "GUILD_UPDATE";
pub const EVENT_GUILD_DELETE: &str = "GUILD_DELETE";
pub const EVENT_CHANNEL_CREATE: &str = "CHANNEL_CREATE";
pub const EVENT_CHANNEL_UPDATE: &str = "CHANNEL_UPDATE";
pub const EVENT_CHANNEL_DELETE: &str = "CHANNEL_DELETE";
pub const EVENT_GUILD_MEMBER_ADD: &str = "GUILD_MEMBER_ADD";
pub const EVENT_GUILD_MEMBER_UPDATE: &str = "GUILD_MEMBER_UPDATE";
pub const EVENT_GUILD_MEMBER_REMOVE: &str = "GUILD_MEMBER_REMOVE";
pub const EVENT_MESSAGE_CREATE: &str = "MESSAGE_CREATE";
pub const EVENT_MESSAGE_REACTION_ADD: &str = "MESSAGE_REACTION_ADD";
pub const EVENT_MESSAGE_REACTION_REMOVE: &str = "MESSAGE_REACTION_REMOVE";
pub const EVENT_AT_MESSAGE_CREATE: &str = "AT_MESSAGE_CREATE";
pub const EVENT_PUBLIC_MESSAGE_DELETE: &str = "PUBLIC_MESSAGE_DELETE";
pub const EVENT_DIRECT_MESSAGE_CREATE: &str = "DIRECT_MESSAGE_CREATE";
pub const EVENT_DIRECT_MESSAGE_DELETE: &str = "DIRECT_MESSAGE_DELETE";
pub const EVENT_AUDIO_START: &str = "AUDIO_START";
pub const EVENT_AUDIO_FINISH: &str = "AUDIO_FINISH";
pub const EVENT_AUDIO_ON_MIC: &str = "AUDIO_ON_MIC";
pub const EVENT_AUDIO_OFF_MIC: &str = "AUDIO_OFF_MIC";
pub const EVENT_MESSAGE_AUDIT_PASS: &str = "MESSAGE_AUDIT_PASS";
pub const EVENT_MESSAGE_AUDIT_REJECT: &str = "MESSAGE_AUDIT_REJECT";
pub const EVENT_MESSAGE_DELETE: &str = "MESSAGE_DELETE";
pub const EVENT_FORUM_THREAD_CREATE: &str = "FORUM_THREAD_CREATE";
pub const EVENT_FORUM_THREAD_UPDATE: &str = "FORUM_THREAD_UPDATE";
pub const EVENT_FORUM_THREAD_DELETE: &str = "FORUM_THREAD_DELETE";
pub const EVENT_FORUM_POST_CREATE: &str = "FORUM_POST_CREATE";
pub const EVENT_FORUM_POST_DELETE: &str = "FORUM_POST_DELETE";
pub const EVENT_FORUM_REPLY_CREATE: &str = "FORUM_REPLY_CREATE";
pub const EVENT_FORUM_REPLY_DELETE: &str = "FORUM_REPLY_DELETE";
pub const EVENT_FORUM_AUDIT_RESULT: &str = "FORUM_PUBLISH_AUDIT_RESULT";
pub const EVENT_INTERACTION_CREATE: &str = "INTERACTION_CREATE";
pub const EVENT_GROUP_AT_MESSAGE_CREATE: &str = "GROUP_AT_MESSAGE_CREATE";
pub const EVENT_C2C_MESSAGE_CREATE: &str = "C2C_MESSAGE_CREATE";
pub const EVENT_SUBSCRIBE_MESSAGE_STATUS: &str = "SUBSCRIBE_MESSAGE_STATUS";
pub const EVENT_C2C_FRIEND_ADD: &str = "FRIEND_ADD";
pub const EVENT_C2C_FRIEND_DEL: &str = "FRIEND_DEL";
pub const EVENT_ENTER_AIO: &str = "ENTER_AIO";
