name: Rust

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Build
              run: cargo build && cargo build --examples --features=examples
            - name: Run tests
              run: cargo test && cargo test --examples --features examples
            - name: Run clippy
              run: cargo clippy && cargo clippy --examples --features examples
